---
- name: Install apt packages for python development
  apt: name={{item}}
  with_items:
    - binutils 
    - libproj-dev 
    - gdal-bin 
    - gettext
    - build-essential 
    - libssl-dev 
    - libffi-dev 
    - python3-dev 
    - python3-pip 
    - python3-venv
    - virtualenv

- name: Create dir for project
  file: path={{ project_dir }}  state=directory
